version: "3.3"
services:
  db:
    image: postgres:15
    container_name: postgres-cryptotrendanalyzer
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-cryptotrendanalyzer}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - cryptotrendanalyzer-db:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    networks:
      - cryptotrendanalyzer-net

  cryptotrendanalyzer-api:
    image: cryptotrendanalyzer-api:latest
    container_name: cryptotrendanalyzer-api
    depends_on:
      - db
    env_file:
      - app/.env
    command: sh -c "pipenv run python manage.py collectstatic --noinput &&
      pipenv run python manage.py makemigrations --noinput &&
      pipenv run python manage.py migrate --noinput &&
      pipenv run python manage.py runserver 0.0.0.0:8000"
    # command: tail -f /dev/null
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    networks:
      - cryptotrendanalyzer-net
    healthcheck:
      test:
        ["CMD-SHELL", "curl -f http://localhost:8000/api/healthcheck || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: on-failure

networks:
  cryptotrendanalyzer-net:

volumes:
  cryptotrendanalyzer-db:
